name: rnn
channels:
  - defaults
dependencies:
  - dask=0.18.1
  - dask-core=0.18.1
  - distributed=1.28.1
  - pandas=0.23.3
  - pip=19.3.1
  - py=1.8.0
  - pyparsing=2.4.5
  - pytest=3.6.3
  - python=3.6.7
  - python-dateutil=2.8.1
  - setuptools=41.6.0
  - sqlite=3.30.1
  - tqdm=4.19.5
  - pip:
    - axelrod==4.2.0
    - ipykernel==5.1.3
    - ipython==5.0.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - matplotlib==3.1.1
    - nltk==3.4.5
    - notebook==6.0.2
    - numpy==1.17.4
    - prompt-toolkit==1.0.18
    - scikit-learn==0.22
    - scipy==1.3.2
    - sklearn==0.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0